let availablekeywords = [
    'Chirag Farsan',
    'Chirag',
    'Farsan',
    'Lasun Chivda',
    'Bharkarwadi',
    'Mitha Namkeen',
    'Lasun Namkeen',
    'Tikha Namkeen',
    'Misal Namkeen',
    'Gathiya Namkeen',
    'Bhavnagari Namkeen',
    'Delhi Namkeen',
    'Madras Namkeen',
    'Papdi Namkeen',
    'Golden Namkeen',
    'Chakli',
    'Shankarpali',
    'Shezwan Chakali',
    'Murkur',
    'Kachori',
    'Samosa',
    'Rajgira Laddu',
    'Kela Weffars',
    'Batata Weffar',
    'Butter Chakali White',
    'Butter Chakali Red',
    'Chana Dal',
    'Mung Dal',
    'Upvas Weffar',
    'Farali Chivda',
    'Chana',
    'Shingdana',
    'Kaju Biscuits',
    'Bhel',
    'Chapta Puri',
    'Pani Puri Sev',
    'Naylon Sev',
    'Pani Puri Sev/Naylon Sev',
    'Normal Sev',
    'Sev',
    'Tukda Chakli',
    'Bhaji Sev',
    'Masala Sing',
    'HTML',
    'HTML',
    'HTML',
    'HTML',
    'HTML',
    'HTML',
    'HTML',
];

const resultsBox = document.querySelector(".result-box")